CREATE TABLE tmp_operations.bgv_data (
	name VARCHAR
	,date_of_birth DATE
	,gender VARCHAR
	,mobile VARCHAR
	,email VARCHAR
	,employee_created_on DATE
	,employee_start_date DATE
	,employee_end_date DATE
	,vbn VARCHAR
	,verification_subsription_category VARCHAR
	,verification_report_status VARCHAR
	,final_status VARCHAR
	,address_status VARCHAR
	,document_status VARCHAR
	,court_check_status VARCHAR
	,current_address VARCHAR
	,zipcode VARCHAR
	,ca_status VARCHAR
	,ca_remark VARCHAR
	,ca_requested_on DATE
	,ca_verified_on DATE
	,ca_tat INTEGER
	,aadhar_id VARCHAR
	,aadhar_detail VARCHAR
	,aadhar_status VARCHAR
	,aadhar_remark VARCHAR
	,ac_requested_on DATE
	,ac_verified_on DATE
	,ac_tat INTEGER
	,pan_id VARCHAR
	,pan_detail VARCHAR
	,pan_status VARCHAR
	,pan_remark VARCHAR
	,pan_requested_on DATE
	,pan_verified_on DATE
	,pan_tat INTEGER
	,dl_id VARCHAR
	,dl_details VARCHAR
	,STATE VARCHAR
	,dl_status VARCHAR
	,dl_remark VARCHAR
	,dl_requested_on DATE
	,dl_verified_on DATE
	,dl tat INTEGER
	,court_record VARCHAR
	,cr_status VARCHAR
	,crc_manual_review_tat INTEGER
	,crc_closed_tat INTEGER
	,cr_requested_on DATE
	,cr_verified_on DATE
	,crc_tat INTEGER
	);
